// ===== Plotter Settings =====

const BED_WIDTH = 220;
const BED_HEIGHT = 220;

const IMAGE_MARGIN = 15;
const MARGIN = 10;

const PEN_UP = 10;
const PEN_DOWN = 0;

const DRAW_FEED = 2500;
const TRAVEL_FEED = 5000;
const Z_FEED = 1000;

export function generateGCode(shapes) {

    if (shapes.length === 0) {
        return "; No shapes to export";
    }

    // =============================
    // Find Drawing Bounds
    // =============================

    let minX = Infinity;
    let minY = Infinity;
    let maxX = -Infinity;
    let maxY = -Infinity;

    shapes.forEach(shape => {

        if (shape.type === "pencil" || shape.type === "line") {

            for (let i = 0; i < shape.points.length; i += 2) {

                const x = shape.points[i];
                const y = shape.points[i + 1];

                minX = Math.min(minX, x);
                minY = Math.min(minY, y);

                maxX = Math.max(maxX, x);
                maxY = Math.max(maxY, y);
            }
        }

        if (shape.type === "rectangle") {

            const left = Math.min(shape.x, shape.x + shape.width);
            const right = Math.max(shape.x, shape.x + shape.width);

            const top = Math.min(shape.y, shape.y + shape.height);
            const bottom = Math.max(shape.y, shape.y + shape.height);

            minX = Math.min(minX, left);
            minY = Math.min(minY, top);

            maxX = Math.max(maxX, right);
            maxY = Math.max(maxY, bottom);
        }

        if (shape.type === "circle") {

            minX = Math.min(minX, shape.x - shape.radius);
            minY = Math.min(minY, shape.y - shape.radius);

            maxX = Math.max(maxX, shape.x + shape.radius);
            maxY = Math.max(maxY, shape.y + shape.radius);
        }

    });

    const drawingWidth = Math.max(maxX - minX, 1);
    const drawingHeight = Math.max(maxY - minY, 1);

    const scale = Math.min(
        (BED_WIDTH - IMAGE_MARGIN * 2) / drawingWidth,
        (BED_HEIGHT - IMAGE_MARGIN * 2) / drawingHeight
    );

    const offsetX =
        (BED_WIDTH - drawingWidth * scale) / 2;

    const offsetY =
        (BED_HEIGHT - drawingHeight * scale) / 2;

    function tx(x) {
        return ((x - minX) * scale + offsetX).toFixed(2);
    }

    function ty(y) {
        return ((y - minY) * scale + offsetY).toFixed(2);
    }

    // =============================
    // Header
    // =============================

    let gcode = "";

    gcode += "; Generated by Outpost Drawing Tool\n";
    gcode += "G21 ; millimeters\n";
    gcode += "G90 ; absolute positioning\n";
    gcode += "G28 ; home all axes\n\n";

    gcode += `G0 Z${PEN_UP} F${Z_FEED}\n`;
    gcode += `G0 X0 Y0 F${TRAVEL_FEED}\n\n`;

    // =============================
    // Shapes
    // =============================

    shapes.forEach(shape => {

        // -------------------------
        // Pencil
        // -------------------------

        if (shape.type === "pencil") {

            const pts = shape.points;

            gcode += "; Pencil\n";

            gcode +=
                `G0 X${tx(pts[0])} Y${ty(pts[1])} F${TRAVEL_FEED}\n`;

            gcode +=
                `G1 Z${PEN_DOWN} F${Z_FEED}\n`;

            for (let i = 0; i < pts.length; i += 2) {

                gcode +=
                    `G1 X${tx(pts[i])} Y${ty(pts[i + 1])} F${DRAW_FEED}\n`;

            }

            gcode +=
                `G0 Z${PEN_UP} F${Z_FEED}\n\n`;
        }

        // -------------------------
        // Line
        // -------------------------

        if (shape.type === "line") {

            gcode += "; Line\n";

            gcode +=
                `G0 X${tx(shape.points[0])} Y${ty(shape.points[1])} F${TRAVEL_FEED}\n`;

            gcode +=
                `G1 Z${PEN_DOWN} F${Z_FEED}\n`;

            gcode +=
                `G1 X${tx(shape.points[2])} Y${ty(shape.points[3])} F${DRAW_FEED}\n`;

            gcode +=
                `G0 Z${PEN_UP} F${Z_FEED}\n\n`;
        }

        // -------------------------
        // Rectangle
        // -------------------------

        if (shape.type === "rectangle") {

            const left = Math.min(shape.x, shape.x + shape.width);
            const right = Math.max(shape.x, shape.x + shape.width);

            const top = Math.min(shape.y, shape.y + shape.height);
            const bottom = Math.max(shape.y, shape.y + shape.height);

            const x1 = tx(left);
            const y1 = ty(top);

            const x2 = tx(right);
            const y2 = ty(bottom);

            gcode += "; Rectangle\n";

            gcode +=
                `G0 X${x1} Y${y1} F${TRAVEL_FEED}\n`;

            gcode +=
                `G1 Z${PEN_DOWN} F${Z_FEED}\n`;

            gcode +=
                `G1 X${x2} Y${y1} F${DRAW_FEED}\n`;

            gcode +=
                `G1 X${x2} Y${y2} F${DRAW_FEED}\n`;

            gcode +=
                `G1 X${x1} Y${y2} F${DRAW_FEED}\n`;

            gcode +=
                `G1 X${x1} Y${y1} F${DRAW_FEED}\n`;

            gcode +=
                `G0 Z${PEN_UP} F${Z_FEED}\n\n`;
        }

        // -------------------------
        // Circle
        // -------------------------

        if (shape.type === "circle") {

            const segments = 100;

            const startX =
                shape.x + shape.radius;

            const startY =
                shape.y;

            gcode += "; Circle\n";

            gcode +=
                `G0 X${tx(startX)} Y${ty(startY)} F${TRAVEL_FEED}\n`;

            gcode +=
                `G1 Z${PEN_DOWN} F${Z_FEED}\n`;

            for (let i = 0; i <= segments; i++) {

                const angle =
                    (Math.PI * 2 * i) / segments;

                const x =
                    shape.x +
                    Math.cos(angle) * shape.radius;

                const y =
                    shape.y +
                    Math.sin(angle) * shape.radius;

                gcode +=
                    `G1 X${tx(x)} Y${ty(y)} F${DRAW_FEED}\n`;
            }

            gcode +=
                `G0 Z${PEN_UP} F${Z_FEED}\n\n`;
        }

    });

    // =============================
    // Finish
    // =============================

    gcode += `G0 Z${PEN_UP} F${Z_FEED}\n`;
    gcode += `G0 X0 Y0 F${TRAVEL_FEED}\n`;
    gcode += "M84 ; disable steppers\n";

    return gcode;
}